version: "3.9"
services:
  # ============================
  # DATABASE POSTGRESQL - Shared
  # ============================
  postgres:
    image: postgres:15-alpine
    container_name: orthanc-postgres-db
    hostname: postgres
    environment:
      POSTGRES_USER: orthanc
      POSTGRES_PASSWORD: ${ORTHANC_DB_PASSWORD}
      TZ: Asia/Ho_Chi_Minh
    command: 
      - "postgres"
      - "-c"
      - "max_connections=${POSTGRES_MAX_CONNECTIONS}"
      - "-c"
      - "shared_buffers=${POSTGRES_SHARED_BUFFERS}"
    volumes:
      - ./data/postgres-db:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orthanc -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - pacs-net
    ports:
      - "${POSTGRES_PORT}:5432"

  # ======================================
  # ORTHANC INSTANCE - Multi-tenant (Modalities)
  # ======================================
  orthanc-multitenant:
    build: .
    container_name: orthanc-multitenant
    hostname: orthanc-multitenant
    ports:
      - "${ORTHANC_HTTP_PORT}:8042"
      - "${ORTHANC_DICOM_PORT}:4243"
      - "4244:4244"
      - "4245:4245"
      - "4246:4246"
      - "4247:4247"
      - "4248:4248"
    volumes:
      - ./config/orthanc.json:/etc/orthanc/orthanc.json:ro
      - ./data/storage-main:/var/lib/orthanc/db
      - ./plugins:/usr/share/orthanc/plugins
      - ./data/worklists:/var/lib/orthanc/worklists
      - ./plugins/gw_plugin.py:/usr/share/orthanc/plugins/gw_plugin.py:ro
      - ./orthanc-log:/var/log/orthanc
    environment:
      # Site info
      SITE_UUID: ${SITE_UUID}
      SITE_NAME: ${SITE_NAME}
      SITE_LOCATION: ${SITE_LOCATION}
      
      # Database
      ORTHANC__POSTGRESQL__ENABLE: "true"
      ORTHANC__POSTGRESQL__HOST: "postgres"
      ORTHANC__POSTGRESQL__PORT: "5432"
      ORTHANC__POSTGRESQL__DATABASE: ${DB_MAIN}
      ORTHANC__POSTGRESQL__USER: "orthanc"
      ORTHANC__POSTGRESQL__PASSWORD: ${ORTHANC_DB_PASSWORD}
      
      # PACS Configuration
      PACS_AET: ${PACS_AET}
      DATACENTER_PACS: "DATACENTER_PACS"
      DATACENTER_AET: ${DATACENTER_AET}
      DATACENTER_IP: ${DATACENTER_IP}
      DATACENTER_PORT: ${DATACENTER_PORT}
      
      # Orthanc settings
      ORTHANC__DICOM_AET: ${PACS_AET}
      ORTHANC__SERIES_STABLE_DELAY: ${SERIES_STABLE_DELAY}
      ORTHANC__HTTP_TLS_ENABLED: "false"
      ORTHANC__HTTP_AUTHENTICATION_ENABLED: "false"
      ORTHANC__LUA_EXECUTION_ENABLED: "true"
      ORTHANC__STORAGE_COMPRESSION: "true"
      ORTHANC__JPEG_QUALITY: 90
      ORTHANC__MONITORING__ENABLED: "true"
      
      # Performance
      CONCURRENT_JOBS: ${CONCURRENT_JOBS}
      DICOM_THREADS_COUNT: ${DICOM_THREADS_COUNT}
      MAXIMUM_STORAGE_SIZE: ${MAXIMUM_STORAGE_SIZE}
      HTTP_TIMEOUT: ${HTTP_TIMEOUT}
      CHUNK_SIZE: ${CHUNK_SIZE}
      MAX_RETRIES: ${MAX_RETRIES}
      
      # Telerad integration
      ENABLE_TELERAD: ${ENABLE_TELERAD}
      TELERAD_URL: ${TELERAD_URL}
      SECRET_KEY: ${SECRET_KEY}
      
      # Worklist
      WORKLIST_FOLDER: ${WORKLIST_FOLDER}
      WORKLIST_PULL_INTERVAL: ${WORKLIST_PULL_INTERVAL}
      
      # Cleanup
      CLEANUP_INTERVAL_HOURS: ${CLEANUP_INTERVAL_HOURS}
      DELETE_OLDER_THAN_DAYS: ${DELETE_OLDER_THAN_DAYS}
      
      # Logging
      DETAIL_LOG_FILE: ${DETAIL_LOG_FILE}
      HEALTH_LOG_FILE: ${HEALTH_LOG_FILE}
      HEALTH_INTERVAL_MINUTES: ${HEALTH_INTERVAL_MINUTES}
      
      # Encoding
      PYTHONIOENCODING: utf-8
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - pacs-net


  # ======================================
  # ORTHANC INSTANCE - Worklist Server
  # ======================================
  orthanc-worklist:
    image: orthancteam/orthanc:latest
    container_name: orthanc-worklist
    hostname: orthanc-worklist
    ports:
      - "${WORKLIST_HTTP_PORT}:8042"
      - "${WORKLIST_DICOM_PORT}:4242"
    volumes:
      - ./config/orthanc-wl.json:/etc/orthanc/orthanc.json:ro
      - ./data/worklists:/var/lib/orthanc/worklists
      - ./plugins:/usr/share/orthanc/plugins
    environment:
      # Database
      ORTHANC__POSTGRESQL__ENABLE: "true"
      ORTHANC__POSTGRESQL__HOST: "postgres"
      ORTHANC__POSTGRESQL__PORT: "5432"
      ORTHANC__POSTGRESQL__DATABASE: ${DB_WORKLIST}
      ORTHANC__POSTGRESQL__USER: "orthanc"
      ORTHANC__POSTGRESQL__PASSWORD: ${ORTHANC_DB_PASSWORD}
      
      # Worklist settings
      WORKLIST_FOLDER: ${WORKLIST_FOLDER}
      WORKLIST_PULL_INTERVAL: ${WORKLIST_PULL_INTERVAL}
      
      # Orthanc settings
      ORTHANC__HTTP_TLS_ENABLED: "false"
      ORTHANC__HTTP_AUTHENTICATION_ENABLED: "false"
      ORTHANC__LUA_EXECUTION_ENABLED: "true"
      ORTHANC__STORAGE_COMPRESSION: "true"
      ORTHANC__JPEG_QUALITY: 90
      
      # Encoding
      PYTHONIOENCODING: utf-8
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - pacs-net

# ============================
# VOLUMES & NETWORKS
# ============================
volumes:
  grafana-storage: {}

networks:
  pacs-net:
    driver: bridge