services:
  wireguard:
    image: linuxserver/wireguard
    container_name: vpn-site-client
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    # Client khong can mo port
    sysctls:
      - net.ipv4.ip_forward=1
    restart: unless-stopped